site_name: klask
site_description: Surfly Assignment
repo_url: https://github.com/aigeano/klask
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/aigeano">aigeano</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
